Repository CourseOrchestra/celesta, pull requests merged in 2020-02, with the labels that each got.

#238 Edited version of English documentation
  .github/release-drafter.yml
  celesta-documentation/src/main/asciidoc/en/1010_what_is_celesta.adoc
  celesta-documentation/src/main/asciidoc/en/1012_demo.adoc
  celesta-documentation/src/main/asciidoc/en/1013_maven_plugin.adoc
  celesta-documentation/src/main/asciidoc/en/1015_vocabulary.adoc
  celesta-documentation/src/main/asciidoc/en/1020_celesta_start.adoc
  celesta-documentation/src/main/asciidoc/en/1040_system_tables.adoc
  celesta-documentation/src/main/asciidoc/en/1050_celesta_sql.adoc
  celesta-documentation/src/main/asciidoc/en/1060_celesta_doc.adoc
  celesta-documentation/src/main/asciidoc/en/1070_call_context.adoc
  celesta-documentation/src/main/asciidoc/en/1080_classes.adoc
  celesta-documentation/src/main/asciidoc/en/1090_blob.adoc
  celesta-documentation/src/main/asciidoc/en/1100_option.adoc
  celesta-documentation/src/main/asciidoc/en/1105_triggers.adoc
  celesta-documentation/src/main/asciidoc/en/1107_xrec.adoc
  celesta-documentation/src/main/asciidoc/en/1110_lost_updates.adoc
  celesta-documentation/src/main/asciidoc/en/1120_meta.adoc
  celesta-documentation/src/main/asciidoc/en/1130_celesta_unit.adoc
  celesta-documentation/src/main/asciidoc/en/2005_best_practices.adoc
  celesta-documentation/src/main/asciidoc/en/2010_supported_rdbms.adoc
  celesta-documentation/src/main/asciidoc/en/2020_dbschema.adoc
  celesta-documentation/src/main/asciidoc/table.adoc
  dict-en
Labels: documentation

#240 Bugfix: BasicTable.delete() doesn't remove metadata completely
  celesta-sql/src/main/java/ru/curs/celesta/score/Grain.java
  celesta-sql/src/test/java/ru/curs/celesta/score/GrainModelTest.java
Labels: bug

#242 Add @Generated annotation for generated Cursor classes
  celesta-maven-plugin/src/main/java/ru/curs/celesta/plugin/maven/CursorGenerator.java
  celesta-maven-plugin/src/test/java/ru/curs/celesta/plugin/maven/AbstractCelestaMojoTestCase.java
  celesta-maven-plugin/src/test/resources/gen-cursors/expectedGenerationResults/data/table/TestRoTableCursor.java
  celesta-maven-plugin/src/test/resources/gen-cursors/expectedGenerationResults/data/table/TestTableCursor.java
  celesta-maven-plugin/src/test/resources/gen-cursors/expectedGenerationResults/data/view/TestTableMvCursor.java
  celesta-maven-plugin/src/test/resources/gen-cursors/expectedGenerationResults/data/view/TestTablePvCursor.java
  celesta-maven-plugin/src/test/resources/gen-cursors/expectedGenerationResults/data/view/TestTableVCursor.java
  celesta-maven-plugin/src/test/resources/gen-cursors/expectedGenerationResults/seq/SeqSequence.java
  pom.xml
Labels: enhancement
